module.exports = {
    info: {
        name: "macedon",
        description: "-",
        usage: "-",
        cooldown: 0,
    },
    execute(client, message, args, Discord) {
        var title = `Alexander's Speech.\n`
        var one = `"The speech which I am about to deliver will not be for the purpose of checking your start homeward, for, so far as I am concerned, you may depart wherever you wish; but because I wish you to know what kind of men you were originally and how you have been transformed since you came into our service. In the first place, as is reasonable, I shall begin my speech from my father Philip. For he found you vagabonds and destitute of means, most of you clad in hides, feeding a few sheep up the mountain sides, for the protection of which you had to fight with small success against Illyrians, Triballians, and the border Thracians. Instead of the hides he gave you cloaks to wear, and from the mountains he led you down into the plains, and made you capable of fighting the neighbouring barbarians, so that you were no longer compelled to preserve yourselves by trusting rather to the inaccessible strongholds than to your own valour. He made you colonists of cities, which he adorned with useful laws and customs; and from being slaves and subjects, he made you rulers over those very barbarians by whom you yourselves, as well as your property, were previously liable to be plundered and ravaged. He also added the greater part of Thrace to Macedonia, and by seizing the most conveniently situated places on the sea-coast, he spread abundance over the land from commerce, and made the working of the mines a secure employment. He made you rulers over the Thessalians, of whom you had formerly been in mortal fear; and by humbling the nation of the Phocians, he rendered the avenue into Greece broad and easy for you, instead of being narrow and difficult. The Athenians and Thebans, who were always lying in wait to attack Macedonia, he humbled to such a degree,—I also then rendering him my personal aid in the campaign,—that instead of paying tribute to the former and being vassals to the latter, those States in their turn procure security to themselves by our assistance.`
        var two = `He penetrated into the Peloponnese, and after regulating its affairs, was publicly declared commander-in-chief of all the rest of Greece in the expedition against the Persian, adding this glory not more to himself than to the commonwealth of the Macedonians. These were the advantages which accrued to you from my father Philip; great indeed if looked at by themselves, but small if compared with those you have obtained from me. For though I inherited from my father only a few gold and silver goblets, and there were not even sixty talents in the treasury, and though I found myself charged with a debt of 500 talents owing by Philip, and I was obliged myself to borrow 800 talents in addition to these, I started from the country which could not decently support you, and forthwith laid open to you the passage of the Hellespont, though at that time the Persians held the sovereignty of the sea. Having overpowered the viceroys of Darius with my cavalry, I added to your empire the whole of Ionia, the whole of Aeolis, both Phrygias and Lydia, and I took Miletus by siege. All the other places I gained by voluntary surrender, and I granted you the privilege of appropriating the wealth found in them. The riches of Egypt and Cyrene, which I acquired without fighting a battle, have come to you. Coele-Syria, Palestine, and Mesopotamia are your property. Babylon, Bactra, and Susa are yours.`
        var three = `The wealth of the Lydians, the treasures of the Persians, and the riches of the Indians are yours; and so is the External Sea. You are viceroys, you are generals, you are captains. What then have I reserved to myself after all these labours, except this purple robe and this diadem? I have appropriated nothing myself, nor can any one point out my treasures, except these possessions of yours or the things which I am guarding on your behalf. Individually, however, I have no motive to guard them, since I feed on the same fare as you do, and I take only the same amount of sleep. Nay, I do not think that my fare is as good as that of those among you who live luxuriously; and I know that I often sit up at night to watch for you, that you may be able to sleep.`
        var four = `But some one may say, that while you endured toil and fatigue, I have acquired these things as your, leader without myself sharing the toil and fatigue. But who is there of you who" knows that he has endured greater toil for me than I have for him? Come now! whoever of you has wounds, let him strip and show them, and I will show mine in turn; for there is no part of my body, in front at any rate, remaining free from wounds; nor is there any kind of weapon used either for close combat or for hurling at the enemy, the traces of which I do not bear on my person. For I have been wounded with the sword in close fight, I have been shot with arrows, and I have been struck with missiles projected from engines of war; and though oftentimes I have been hit with stones and bolts of wood for the sake of your lives, your glory, and your wealth, I am still leading you as conquerors over all the land and sea, all rivers, mountains, and plains. I have celebrated your weddings with my own, and the children of many of you will be akin to my children. Moreover I have liquidated the debts of all those who had incurred them, without inquiring too closely for what purpose they were contracted, though you receive such high pay, and carry off so much booty whenever there is booty to be got after a siege. Most of you have golden crowns, the eternal memorials of your valour and of the honour you receive from me. Whoever has been killed, has met with a glorious end and has been honoured with a splendid burial. Brazen statues of most of the slain have been erected at home, and their parents are held in honour, being released from all public service and from taxation.`
        var five = `But no one of you has ever been killed in flight under my leadership. And now I was intending to send back those of you who are unfit for service, objects of envy to those at home; but since you all wish to depart, depart all of you! Go back and report at home that your king Alexander, the conqueror of the Persians, Medes, Bactrians, and Sacians; the man who has subjugated the Uxians, Arachotians, and Drangians; who has also acquired the rule of the Parthians, Chorasmians, and Hyrcanians, as far as the Caspian Sea; who has marched over the Caucasus, through the Caspian Gates; who has crossed the rivers Oxus and Tanais, and the Indus besides, which has never been crossed by any one else except Dionysus; who has also crossed the Hydaspes, Acesines, and Hydraotes, and who would have crossed the Hyphasis, if you had not shrunk back with alarm; who has penetrated into the Great Sea by both the mouths of the Indus; who has marched through the desert of Gadrosia, where no one ever before marched with an army; who on his route acquired possession of Carmania and the land of the Oritians, in addition to his other conquests, his fleet having in the meantime already sailed round the coast of the sea which extends from India to Persia—report that when you returned to Susa you deserted him and went away, handing him over to the protection of conquered foreigners. Perhaps this report of yours will be both glorious to you in the eyes of men and devout forsooth in the eyes of the gods. Depart!"`
        message.channel.send(title)
        message.channel.send(one)
        message.channel.send(two)
        message.channel.send(three)
        message.channel.send(four)
        message.channel.send(five)
    }
}